data:
  target_col: "sentiment"
  meta_cols:
    - "qm_density"
    - "em_density"
    - "uppercase_count"
    - "vader_compound"
    - "word_count"
    - "TTR"

experiment:
  name: "imdb_sentiment_baseline"
  n_trials: 20
  random_state: 42
  n_splits: 5
  inner_splits: 3

tfidf:
  max_features:
    low: 5000
    high: 20000
    step: 1000     # Optuna will suggest_int with this step
  ngram_range:
    - [1, 1]
    - [1, 2]       # Optuna will suggest_categorical from this list
  use_idf:
    - True
    - False

catboost:
  static:
    loss_function: 'Logloss'
    eval_metric: 'AUC'
    task_type: 'CPU'
    thread_count: -1       # Utilize all 96 CPU threads
    verbose: 0

  search_space:
    iterations:
      low: 200
      high: 1500
    depth:
      low: 4
      high: 10
    learning_rate:
      low: 0.01
      high: 0.3
    l2_leaf_reg:
      low: 1.0
      high: 10.0

bert:
  model_name: "distilbert-base-uncased"
  batch_size: 256
  max_length: 256

production:
  name: "imdb_sentiment_production"
  n_trials: 20
  catboost:
    static:
      loss_function: 'Logloss'
      eval_metric: 'AUC'
      task_type: 'GPU'
      devices: '0'
      verbose: 0
    search_space:
      iterations:
        low: 500
        high: 3000
      depth:
        low: 4
        high: 10
      learning_rate:
        low: 0.01
        high: 0.3
      l2_leaf_reg:
        low: 1.0
        high: 10.0

neural_classifiers:
  name: "imdb_sentiment_neural"
  n_trials: 20
  logreg:
    C:
      low: 1e-4
      high: 1e2
    l1_ratio:
      low: 0.0
      high: 1.0
  mlp:
    n_layers:
      low: 1
      high: 3
    n_units: [16, 32, 64, 128, 256, 512]
    dropout:
      low: 0.1
      high: 0.6
    lr:
      low: 1e-5
      high: 1e-2
    weight_decay:
      low: 1e-6
      high: 1e-1
    batch_size: 2048
    epochs: 100
    patience: 10

meta_only:
  name: "imdb_sentiment_meta_only"
  n_trials: 20
  catboost:
    static:
      loss_function: 'Logloss'
      eval_metric: 'AUC'
      task_type: 'CPU'
      thread_count: -1
      verbose: 0
    search_space:
      iterations:
        low: 200
        high: 1500
      depth:
        low: 4
        high: 8
      learning_rate:
        low: 0.01
        high: 0.3
      l2_leaf_reg:
        low: 1.0
        high: 10.0
